version: '3'

volumes: 
  mysql_data:

services: 
  mysql:
    container_name: ${PROJECT}.mysql
    image: mysql:5.7.26
    environment: 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    ports: 
      - 3306:3306

  adminer:
    container_name: ${PROJECT}.adminer
    image: adminer:latest
    restart: always
    depends_on:
      - mysql
    environment: 
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_HOST=${PROJECT}.mysql
      - ADMINER_DEFAULT_DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    
  api:
    container_name: ${PROJECT}.api
    image: ${PROJECT}.api:dev-${TAG}
    restart: ${SERVICES_RESTART_TYPE}
    env_file: 
      - .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 42001:3000